runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -t 3600 --keep-alive 300 main:app

runtime_config:
  python_version: 3

  #[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: foodhud-project.appspot.com
#[END env]
